### ISSUE TITLE
createlang plpython fails

### ISSUE THREAD

**Issue by natea** [opendataphilly/Open-Data-Catalog#20]
Can Open-Data-Catalog be run on MacOSX? I'm trying to use it with Postgres.app, and getting this error:

```
$ createlang plpython
createlang: language installation failed: ERROR:  could not open extension control file "/Applications/Postgres.app/Contents/MacOS/share/extension/plpython.control": No such file or directory
```

**Comment by jwalgran** [comment]
It appears that the source of your problem is with OS X, but with the Postgress.app pre-built application.

OpenDataCatalog makes use of Postgres functions written in [plpython](http://www.postgresql.org/docs/9.0/static/plpython.html). Here is the section from the plpython documentation that explains why it is probably not working in Postgress.app

```
Note: Users of source packages must specially enable the build of PL/Python
during the installation process. (Refer to the installation instructions for more
information.) Users of binary packages might find PL/Python in a separate subpackage.
```

It might be worth talking to the maintainers of Postgres.app to see if they are planning to add support for plpython.

**Comment by bcavagnolo** [comment]
BTW, I got this same error on Ubuntu 12.04.  But it just turned out that postgresql-plpython-9.1 was not installed.  Maybe just add this to the dependency list?
